### PR TITLE
Implement overhead benchmark 

### PR DESCRIPTION
**Pull request by mxpv**
This PR adds an `overhead` command line flag to measure overhead (memory and cpu usage of a daemon and it's child processes) between different container implementations.

Implementation notes:
- Original docker driver was renamed to DockerCLI
- Docker API driver was added for more precise comparison between containerd and docker
- Some things were refactored to look more ‘go way’ (driver interface now accepts context and returns time.Duration instead of int)

Caveats:
- Implementation only covers `Docker` and `Containerd`.
- The benchmark uses process name matching to find relevant processes; you must keep the expected process names (`dockerd`, `docker-containerd`, and `docker-containerd-shim` for Docker and `containerd` and `containerd-shim` for containerd) and not run additional processes with the same names (possibly will be reworked in favor of cgroups)
- This also lets you enable a log driver in Docker, but no log sink in the other runtimes

The output looks like this:

```
OVERHEAD

    Bench / driver / threads       Min       Max       Avg       Min       Max       Avg     Mem %     CPU x
  OverheadBench:Containerd:1     46 MB     47 MB     46 MB    0.00 %    6.07 %    0.43 %
  OverheadBench:Containerd:2     44 MB     63 MB     50 MB    0.00 %   11.61 %    0.66 %
  OverheadBench:Containerd:3     55 MB     79 MB     57 MB    0.00 %   18.64 %    0.84 %
  OverheadBench:Containerd:4     51 MB     64 MB     61 MB    0.00 %   24.51 %    1.05 %
      OverheadBench:Docker:1     67 MB     71 MB     69 MB    0.00 %    9.90 %    0.68 %   +50.00%    +1.58x
      OverheadBench:Docker:2     69 MB     78 MB     75 MB    0.00 %   17.73 %    1.46 %   +50.00%    +2.23x
      OverheadBench:Docker:3     73 MB     81 MB     80 MB    0.00 %   31.27 %    2.01 %   +40.35%    +2.39x
      OverheadBench:Docker:4     71 MB     86 MB     84 MB    0.00 %   29.59 %    2.62 %   +37.70%    +2.48x
```

cc @samuelkarp

### CODE REVIEW

**Comment by estesp** [comment]
Thanks for the contribution @mxpv ; this looks good and has some nice cleanups as well. It might be nice to mention the caveats and limitations (only `Docker` and `Containerd` drivers) of the overhead benchmark as well that you have in the PR comment.

**Comment by mxpv** [comment]
@estesp done!

**Comment by mataneja** [comment]
What versions of Containerd and Docker is the comparison above?

**Comment by mxpv** [comment]
@mataneja `Docker version 1.12.6, build 7392c3b/1.12.6` and `containerd github.com/containerd/containerd v1.1.3 8f54c750c67e87a3b1c218208bbd5cc427c653e9`

**Comment by mataneja** [comment]
@mxpv appreciate the information. I realize that its just an example, can I plz request the comparison with Docker 18.06  and containerd 1.1.3 plz?

**Pull request merged**
