### PR TITLE
Add new mode to reduce number of test suites for multi-thread benchmark

### PR DESCRIPTION
**Pull request by Jeffwan**
Address https://github.com/estesp/bucketbench/issues/76

Update output details for latest mode

Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>

results:

image

legacy mode remains the same
image

### CODE REVIEW

**Comment by estesp** [comment]
Thanks for the contribution! Would you mind adding/editing `README.md` with info about the new flag? There is a description of how "threads" and "iterations" are used, and the [threads](https://github.com/estesp/bucketbench/blob/main/README.md?plain=1#L97) description should be updated to state the difference between legacy mode and the new default path.

**Comment by Jeffwan** [comment]
Sounds good. I will update the README.md

**Comment by Jeffwan** [comment]
@estesp I am a little bit late and docs are updated now. Please have a check and let me know whether further updates needed. https://github.com/estesp/bucketbench/pull/79 has been updated as well.

**Review by estesp — APPROVED** [review]
LGTM

**Comment by estesp** [comment]
Merging your other PR created a conflict; as soon as you resolve and push I'll merge this as well

**Comment by Jeffwan** [comment]
@estesp thanks! I rebase the master and it's up to date

**Review by estesp — APPROVED** [review]

**Comment by estesp** [comment]
Thanks for the contribution!

**Pull request merged**
